
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 67 // CS0067 The event 'event' is never used

using System.ComponentModel;
using System.Globalization;
using Windows.ApplicationModel.Resources;
using Windows.Globalization;
using Windows.UI.Xaml;

namespace PaZword.Localization
{
    public partial class LanguageManager : INotifyPropertyChanged
    {
        private static LanguageManager _languageManager;
		
        private readonly AccountPageStrings _accountpage = new AccountPageStrings();
        private readonly AuthenticationPageStrings _authenticationpage = new AuthenticationPageStrings();
        private readonly BankAccountDataStrings _bankaccountdata = new BankAccountDataStrings();
        private readonly BreachDiscoveredDialogStrings _breachdiscovereddialog = new BreachDiscoveredDialogStrings();
        private readonly CategoryPageStrings _categorypage = new CategoryPageStrings();
        private readonly CoreStrings _core = new CoreStrings();
        private readonly CredentialDataStrings _credentialdata = new CredentialDataStrings();
        private readonly DropboxStrings _dropbox = new DropboxStrings();
        private readonly FileDataStrings _filedata = new FileDataStrings();
        private readonly FirstStartExperiencePageStrings _firststartexperiencepage = new FirstStartExperiencePageStrings();
        private readonly InputDialogStrings _inputdialog = new InputDialogStrings();
        private readonly LicenseKeyDataStrings _licensekeydata = new LicenseKeyDataStrings();
        private readonly MainPageStrings _mainpage = new MainPageStrings();
        private readonly OneDriveStrings _onedrive = new OneDriveStrings();
        private readonly OtherDataStrings _otherdata = new OtherDataStrings();
        private readonly PasswordGeneratorDialogStrings _passwordgeneratordialog = new PasswordGeneratorDialogStrings();
        private readonly PaymentCardDataStrings _paymentcarddata = new PaymentCardDataStrings();
        private readonly RateAndReviewAppStrings _rateandreviewapp = new RateAndReviewAppStrings();
        private readonly SettingsPageStrings _settingspage = new SettingsPageStrings();
        private readonly SetupTwoFactorAuthenticationStrings _setuptwofactorauthentication = new SetupTwoFactorAuthenticationStrings();
        private readonly WiFiCredentialDataStrings _wificredentialdata = new WiFiCredentialDataStrings();

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets an instance of <see cref="LanguageManager"/>.
        /// </summary>
        public static LanguageManager Instance => _languageManager ?? (_languageManager = new LanguageManager());

        /// <summary>
        /// Gets if the text must be written from left to right or from right to left.
        /// </summary>
        public FlowDirection FlowDirection { get; private set; }

        /// <summary>
        /// Gets the <see cref="AccountPageStrings"/>.
        /// </summary>
        public AccountPageStrings AccountPage => _accountpage;

        /// <summary>
        /// Gets the <see cref="AuthenticationPageStrings"/>.
        /// </summary>
        public AuthenticationPageStrings AuthenticationPage => _authenticationpage;

        /// <summary>
        /// Gets the <see cref="BankAccountDataStrings"/>.
        /// </summary>
        public BankAccountDataStrings BankAccountData => _bankaccountdata;

        /// <summary>
        /// Gets the <see cref="BreachDiscoveredDialogStrings"/>.
        /// </summary>
        public BreachDiscoveredDialogStrings BreachDiscoveredDialog => _breachdiscovereddialog;

        /// <summary>
        /// Gets the <see cref="CategoryPageStrings"/>.
        /// </summary>
        public CategoryPageStrings CategoryPage => _categorypage;

        /// <summary>
        /// Gets the <see cref="CoreStrings"/>.
        /// </summary>
        public CoreStrings Core => _core;

        /// <summary>
        /// Gets the <see cref="CredentialDataStrings"/>.
        /// </summary>
        public CredentialDataStrings CredentialData => _credentialdata;

        /// <summary>
        /// Gets the <see cref="DropboxStrings"/>.
        /// </summary>
        public DropboxStrings Dropbox => _dropbox;

        /// <summary>
        /// Gets the <see cref="FileDataStrings"/>.
        /// </summary>
        public FileDataStrings FileData => _filedata;

        /// <summary>
        /// Gets the <see cref="FirstStartExperiencePageStrings"/>.
        /// </summary>
        public FirstStartExperiencePageStrings FirstStartExperiencePage => _firststartexperiencepage;

        /// <summary>
        /// Gets the <see cref="InputDialogStrings"/>.
        /// </summary>
        public InputDialogStrings InputDialog => _inputdialog;

        /// <summary>
        /// Gets the <see cref="LicenseKeyDataStrings"/>.
        /// </summary>
        public LicenseKeyDataStrings LicenseKeyData => _licensekeydata;

        /// <summary>
        /// Gets the <see cref="MainPageStrings"/>.
        /// </summary>
        public MainPageStrings MainPage => _mainpage;

        /// <summary>
        /// Gets the <see cref="OneDriveStrings"/>.
        /// </summary>
        public OneDriveStrings OneDrive => _onedrive;

        /// <summary>
        /// Gets the <see cref="OtherDataStrings"/>.
        /// </summary>
        public OtherDataStrings OtherData => _otherdata;

        /// <summary>
        /// Gets the <see cref="PasswordGeneratorDialogStrings"/>.
        /// </summary>
        public PasswordGeneratorDialogStrings PasswordGeneratorDialog => _passwordgeneratordialog;

        /// <summary>
        /// Gets the <see cref="PaymentCardDataStrings"/>.
        /// </summary>
        public PaymentCardDataStrings PaymentCardData => _paymentcarddata;

        /// <summary>
        /// Gets the <see cref="RateAndReviewAppStrings"/>.
        /// </summary>
        public RateAndReviewAppStrings RateAndReviewApp => _rateandreviewapp;

        /// <summary>
        /// Gets the <see cref="SettingsPageStrings"/>.
        /// </summary>
        public SettingsPageStrings SettingsPage => _settingspage;

        /// <summary>
        /// Gets the <see cref="SetupTwoFactorAuthenticationStrings"/>.
        /// </summary>
        public SetupTwoFactorAuthenticationStrings SetupTwoFactorAuthentication => _setuptwofactorauthentication;

        /// <summary>
        /// Gets the <see cref="WiFiCredentialDataStrings"/>.
        /// </summary>
        public WiFiCredentialDataStrings WiFiCredentialData => _wificredentialdata;

        /// <summary>
        /// Retrieves the current culture.
        /// </summary>
        public CultureInfo GetCurrentCulture()
        {
            return CultureInfo.CurrentUICulture;
        }

        /// <summary>
        /// Change the current culture of the application
        /// </summary>
        public void SetCurrentCulture(CultureInfo culture)
        {
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;
            ApplicationLanguages.PrimaryLanguageOverride = culture.TwoLetterISOLanguageName;

            if (culture.TextInfo.IsRightToLeft)
            {
                FlowDirection = FlowDirection.RightToLeft;
            }
            else
            {
                FlowDirection = FlowDirection.LeftToRight;
            }

            // All the properties changed.
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
        }
    }

    public class AccountPageStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/AccountPage");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource AddData.
        /// </summary>
        public string AddData => _resources.GetString("AddData");

        /// <summary>
        /// Gets the resource AutomationAccountCategory.
        /// </summary>
        public string AutomationAccountCategory => _resources.GetString("AutomationAccountCategory");

        /// <summary>
        /// Gets the resource Cancel.
        /// </summary>
        public string Cancel => _resources.GetString("Cancel");

        /// <summary>
        /// Gets the resource CategoryUncategorized.
        /// </summary>
        public string CategoryUncategorized => _resources.GetString("CategoryUncategorized");

        /// <summary>
        /// Gets the resource DataLengthOutOfRangeCloseButtonText.
        /// </summary>
        public string DataLengthOutOfRangeCloseButtonText => _resources.GetString("DataLengthOutOfRangeCloseButtonText");

        /// <summary>
        /// Gets the resource DataLengthOutOfRangeDescription.
        /// </summary>
        public string DataLengthOutOfRangeDescription => _resources.GetString("DataLengthOutOfRangeDescription");

        /// <summary>
        /// Gets the resource DataLengthOutOfRangeDescription with format.
        /// </summary>
        public string GetFormattedDataLengthOutOfRangeDescription(string param0, string param1, string param2)
        {
            return string.Format(DataLengthOutOfRangeDescription, param0, param1, param2);
        }

        /// <summary>
        /// Gets the resource Delete.
        /// </summary>
        public string Delete => _resources.GetString("Delete");

        /// <summary>
        /// Gets the resource DeleteConfirmationDescription.
        /// </summary>
        public string DeleteConfirmationDescription => _resources.GetString("DeleteConfirmationDescription");

        /// <summary>
        /// Gets the resource DeleteConfirmationTitle.
        /// </summary>
        public string DeleteConfirmationTitle => _resources.GetString("DeleteConfirmationTitle");

        /// <summary>
        /// Gets the resource DeleteConfirmationTitle with format.
        /// </summary>
        public string GetFormattedDeleteConfirmationTitle(string param0)
        {
            return string.Format(DeleteConfirmationTitle, param0);
        }

        /// <summary>
        /// Gets the resource DiscardChanges.
        /// </summary>
        public string DiscardChanges => _resources.GetString("DiscardChanges");

        /// <summary>
        /// Gets the resource DiscardUnsavedChangesConfirmationDescription.
        /// </summary>
        public string DiscardUnsavedChangesConfirmationDescription => _resources.GetString("DiscardUnsavedChangesConfirmationDescription");

        /// <summary>
        /// Gets the resource DiscardUnsavedChangesConfirmationTitle.
        /// </summary>
        public string DiscardUnsavedChangesConfirmationTitle => _resources.GetString("DiscardUnsavedChangesConfirmationTitle");

        /// <summary>
        /// Gets the resource Edit.
        /// </summary>
        public string Edit => _resources.GetString("Edit");

        /// <summary>
        /// Gets the resource Favorite.
        /// </summary>
        public string Favorite => _resources.GetString("Favorite");

        /// <summary>
        /// Gets the resource GeneratePassword.
        /// </summary>
        public string GeneratePassword => _resources.GetString("GeneratePassword");

        /// <summary>
        /// Gets the resource LastModification.
        /// </summary>
        public string LastModification => _resources.GetString("LastModification");

        /// <summary>
        /// Gets the resource LastModification with format.
        /// </summary>
        public string GetFormattedLastModification(string param0, string param1)
        {
            return string.Format(LastModification, param0, param1);
        }

        /// <summary>
        /// Gets the resource MoveDown.
        /// </summary>
        public string MoveDown => _resources.GetString("MoveDown");

        /// <summary>
        /// Gets the resource MoveUp.
        /// </summary>
        public string MoveUp => _resources.GetString("MoveUp");

        /// <summary>
        /// Gets the resource No.
        /// </summary>
        public string No => _resources.GetString("No");

        /// <summary>
        /// Gets the resource Save.
        /// </summary>
        public string Save => _resources.GetString("Save");

        /// <summary>
        /// Gets the resource SaveChanges.
        /// </summary>
        public string SaveChanges => _resources.GetString("SaveChanges");

        /// <summary>
        /// Gets the resource Title.
        /// </summary>
        public string Title => _resources.GetString("Title");

        /// <summary>
        /// Gets the resource TitleIsEmptyDescription.
        /// </summary>
        public string TitleIsEmptyDescription => _resources.GetString("TitleIsEmptyDescription");

        /// <summary>
        /// Gets the resource TitleIsEmptyTitle.
        /// </summary>
        public string TitleIsEmptyTitle => _resources.GetString("TitleIsEmptyTitle");

        /// <summary>
        /// Gets the resource Tutorial.
        /// </summary>
        public string Tutorial => _resources.GetString("Tutorial");

        /// <summary>
        /// Gets the resource Url.
        /// </summary>
        public string Url => _resources.GetString("Url");

        /// <summary>
        /// Gets the resource Yes.
        /// </summary>
        public string Yes => _resources.GetString("Yes");
    }

    public class AuthenticationPageStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/AuthenticationPage");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource CodeGenerated.
        /// </summary>
        public string CodeGenerated => _resources.GetString("CodeGenerated");

        /// <summary>
        /// Gets the resource CodeGeneratedEmail.
        /// </summary>
        public string CodeGeneratedEmail => _resources.GetString("CodeGeneratedEmail");

        /// <summary>
        /// Gets the resource EnterSecretKeyTextBox.
        /// </summary>
        public string EnterSecretKeyTextBox => _resources.GetString("EnterSecretKeyTextBox");

        /// <summary>
        /// Gets the resource RetryAuthentication.
        /// </summary>
        public string RetryAuthentication => _resources.GetString("RetryAuthentication");

        /// <summary>
        /// Gets the resource SecretKeyInstruction.
        /// </summary>
        public string SecretKeyInstruction => _resources.GetString("SecretKeyInstruction");

        /// <summary>
        /// Gets the resource SecretKeyInvalid.
        /// </summary>
        public string SecretKeyInvalid => _resources.GetString("SecretKeyInvalid");

        /// <summary>
        /// Gets the resource SecretKeyTitle.
        /// </summary>
        public string SecretKeyTitle => _resources.GetString("SecretKeyTitle");

        /// <summary>
        /// Gets the resource TwoFactorEmailInstruction.
        /// </summary>
        public string TwoFactorEmailInstruction => _resources.GetString("TwoFactorEmailInstruction");

        /// <summary>
        /// Gets the resource TwoFactorEmailInstruction with format.
        /// </summary>
        public string GetFormattedTwoFactorEmailInstruction(string param0, string param1)
        {
            return string.Format(TwoFactorEmailInstruction, param0, param1);
        }

        /// <summary>
        /// Gets the resource TwoFactorTitle.
        /// </summary>
        public string TwoFactorTitle => _resources.GetString("TwoFactorTitle");

        /// <summary>
        /// Gets the resource TwoFactorUseEmail.
        /// </summary>
        public string TwoFactorUseEmail => _resources.GetString("TwoFactorUseEmail");

        /// <summary>
        /// Gets the resource Welcome.
        /// </summary>
        public string Welcome => _resources.GetString("Welcome");

        /// <summary>
        /// Gets the resource WindowsHelloDisabled.
        /// </summary>
        public string WindowsHelloDisabled => _resources.GetString("WindowsHelloDisabled");

        /// <summary>
        /// Gets the resource WindowsHelloFailed.
        /// </summary>
        public string WindowsHelloFailed => _resources.GetString("WindowsHelloFailed");

        /// <summary>
        /// Gets the resource WindowsHelloTitle.
        /// </summary>
        public string WindowsHelloTitle => _resources.GetString("WindowsHelloTitle");
    }

    public class BankAccountDataStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/BankAccountData");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource AccountHolderName.
        /// </summary>
        public string AccountHolderName => _resources.GetString("AccountHolderName");

        /// <summary>
        /// Gets the resource AccountNumber.
        /// </summary>
        public string AccountNumber => _resources.GetString("AccountNumber");

        /// <summary>
        /// Gets the resource BankName.
        /// </summary>
        public string BankName => _resources.GetString("BankName");

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");

        /// <summary>
        /// Gets the resource IbanNumber.
        /// </summary>
        public string IbanNumber => _resources.GetString("IbanNumber");

        /// <summary>
        /// Gets the resource Pin.
        /// </summary>
        public string Pin => _resources.GetString("Pin");

        /// <summary>
        /// Gets the resource RoutingNumber.
        /// </summary>
        public string RoutingNumber => _resources.GetString("RoutingNumber");

        /// <summary>
        /// Gets the resource SwiftCode.
        /// </summary>
        public string SwiftCode => _resources.GetString("SwiftCode");
    }

    public class BreachDiscoveredDialogStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/BreachDiscoveredDialog");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource BreachInformation.
        /// </summary>
        public string BreachInformation => _resources.GetString("BreachInformation");

        /// <summary>
        /// Gets the resource BreachInformation with format.
        /// </summary>
        public string GetFormattedBreachInformation(string param0, string param1)
        {
            return string.Format(BreachInformation, param0, param1);
        }

        /// <summary>
        /// Gets the resource ImpactedAccountsTitle.
        /// </summary>
        public string ImpactedAccountsTitle => _resources.GetString("ImpactedAccountsTitle");

        /// <summary>
        /// Gets the resource PrimaryButton.
        /// </summary>
        public string PrimaryButton => _resources.GetString("PrimaryButton");

        /// <summary>
        /// Gets the resource RecommendedActions.
        /// </summary>
        public string RecommendedActions => _resources.GetString("RecommendedActions");

        /// <summary>
        /// Gets the resource RecommendedActionsDescription.
        /// </summary>
        public string RecommendedActionsDescription => _resources.GetString("RecommendedActionsDescription");

        /// <summary>
        /// Gets the resource Title.
        /// </summary>
        public string Title => _resources.GetString("Title");

        /// <summary>
        /// Gets the resource WarningIntroduction.
        /// </summary>
        public string WarningIntroduction => _resources.GetString("WarningIntroduction");

        /// <summary>
        /// Gets the resource WarningIntroduction with format.
        /// </summary>
        public string GetFormattedWarningIntroduction(string param0)
        {
            return string.Format(WarningIntroduction, param0);
        }
    }

    public class CategoryPageStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/CategoryPage");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource AddAcount.
        /// </summary>
        public string AddAcount => _resources.GetString("AddAcount");

        /// <summary>
        /// Gets the resource AutomationAccountListDescription.
        /// </summary>
        public string AutomationAccountListDescription => _resources.GetString("AutomationAccountListDescription");

        /// <summary>
        /// Gets the resource Delete.
        /// </summary>
        public string Delete => _resources.GetString("Delete");

        /// <summary>
        /// Gets the resource GeneratePassword.
        /// </summary>
        public string GeneratePassword => _resources.GetString("GeneratePassword");

        /// <summary>
        /// Gets the resource Tutorial.
        /// </summary>
        public string Tutorial => _resources.GetString("Tutorial");
    }

    public class CoreStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/Core");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource CategoryAll.
        /// </summary>
        public string CategoryAll => _resources.GetString("CategoryAll");

        /// <summary>
        /// Gets the resource CategoryFinancial.
        /// </summary>
        public string CategoryFinancial => _resources.GetString("CategoryFinancial");

        /// <summary>
        /// Gets the resource CategoryPersonal.
        /// </summary>
        public string CategoryPersonal => _resources.GetString("CategoryPersonal");

        /// <summary>
        /// Gets the resource CategoryProfessional.
        /// </summary>
        public string CategoryProfessional => _resources.GetString("CategoryProfessional");

        /// <summary>
        /// Gets the resource CategorySocial.
        /// </summary>
        public string CategorySocial => _resources.GetString("CategorySocial");

        /// <summary>
        /// Gets the resource Copy.
        /// </summary>
        public string Copy => _resources.GetString("Copy");

        /// <summary>
        /// Gets the resource Reveal.
        /// </summary>
        public string Reveal => _resources.GetString("Reveal");

        /// <summary>
        /// Gets the resource Synchronizing.
        /// </summary>
        public string Synchronizing => _resources.GetString("Synchronizing");

        /// <summary>
        /// Gets the resource SynchronizingFailed.
        /// </summary>
        public string SynchronizingFailed => _resources.GetString("SynchronizingFailed");

        /// <summary>
        /// Gets the resource SynchronizingSucceeded.
        /// </summary>
        public string SynchronizingSucceeded => _resources.GetString("SynchronizingSucceeded");
    }

    public class CredentialDataStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/CredentialData");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");

        /// <summary>
        /// Gets the resource Email.
        /// </summary>
        public string Email => _resources.GetString("Email");

        /// <summary>
        /// Gets the resource Password.
        /// </summary>
        public string Password => _resources.GetString("Password");

        /// <summary>
        /// Gets the resource SecurityQuestion.
        /// </summary>
        public string SecurityQuestion => _resources.GetString("SecurityQuestion");

        /// <summary>
        /// Gets the resource SecurityQuestionAnswer.
        /// </summary>
        public string SecurityQuestionAnswer => _resources.GetString("SecurityQuestionAnswer");

        /// <summary>
        /// Gets the resource Username.
        /// </summary>
        public string Username => _resources.GetString("Username");
    }

    public class DropboxStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/Dropbox");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");
    }

    public class FileDataStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/FileData");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource BrowseFiles.
        /// </summary>
        public string BrowseFiles => _resources.GetString("BrowseFiles");

        /// <summary>
        /// Gets the resource Description.
        /// </summary>
        public string Description => _resources.GetString("Description");

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");

        /// <summary>
        /// Gets the resource DropFile.
        /// </summary>
        public string DropFile => _resources.GetString("DropFile");

        /// <summary>
        /// Gets the resource FileNotFoundMessage.
        /// </summary>
        public string FileNotFoundMessage => _resources.GetString("FileNotFoundMessage");

        /// <summary>
        /// Gets the resource FileNotFoundMessage with format.
        /// </summary>
        public string GetFormattedFileNotFoundMessage(string param0)
        {
            return string.Format(FileNotFoundMessage, param0);
        }

        /// <summary>
        /// Gets the resource FileNotFoundMessageCloseButtonText.
        /// </summary>
        public string FileNotFoundMessageCloseButtonText => _resources.GetString("FileNotFoundMessageCloseButtonText");

        /// <summary>
        /// Gets the resource FileSizeLimit.
        /// </summary>
        public string FileSizeLimit => _resources.GetString("FileSizeLimit");

        /// <summary>
        /// Gets the resource FileSizeLimit with format.
        /// </summary>
        public string GetFormattedFileSizeLimit(string param0)
        {
            return string.Format(FileSizeLimit, param0);
        }

        /// <summary>
        /// Gets the resource FileSizeTooBig.
        /// </summary>
        public string FileSizeTooBig => _resources.GetString("FileSizeTooBig");

        /// <summary>
        /// Gets the resource NoFile.
        /// </summary>
        public string NoFile => _resources.GetString("NoFile");

        /// <summary>
        /// Gets the resource Or.
        /// </summary>
        public string Or => _resources.GetString("Or");

        /// <summary>
        /// Gets the resource Type.
        /// </summary>
        public string Type => _resources.GetString("Type");

        /// <summary>
        /// Gets the resource ViewFile.
        /// </summary>
        public string ViewFile => _resources.GetString("ViewFile");
    }

    public class FirstStartExperiencePageStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/FirstStartExperiencePage");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource AllFileType.
        /// </summary>
        public string AllFileType => _resources.GetString("AllFileType");

        /// <summary>
        /// Gets the resource AllSetDescription.
        /// </summary>
        public string AllSetDescription => _resources.GetString("AllSetDescription");

        /// <summary>
        /// Gets the resource AllSetTitle.
        /// </summary>
        public string AllSetTitle => _resources.GetString("AllSetTitle");

        /// <summary>
        /// Gets the resource Back.
        /// </summary>
        public string Back => _resources.GetString("Back");

        /// <summary>
        /// Gets the resource Continue.
        /// </summary>
        public string Continue => _resources.GetString("Continue");

        /// <summary>
        /// Gets the resource EnterSecretKeyDescription.
        /// </summary>
        public string EnterSecretKeyDescription => _resources.GetString("EnterSecretKeyDescription");

        /// <summary>
        /// Gets the resource EnterSecretKeyInvalidKeyReasonFileNotFound.
        /// </summary>
        public string EnterSecretKeyInvalidKeyReasonFileNotFound => _resources.GetString("EnterSecretKeyInvalidKeyReasonFileNotFound");

        /// <summary>
        /// Gets the resource EnterSecretKeyInvalidKeyReasonInvalidSecretKey.
        /// </summary>
        public string EnterSecretKeyInvalidKeyReasonInvalidSecretKey => _resources.GetString("EnterSecretKeyInvalidKeyReasonInvalidSecretKey");

        /// <summary>
        /// Gets the resource EnterSecretKeyTextBox.
        /// </summary>
        public string EnterSecretKeyTextBox => _resources.GetString("EnterSecretKeyTextBox");

        /// <summary>
        /// Gets the resource EnterSecretKeyTitle.
        /// </summary>
        public string EnterSecretKeyTitle => _resources.GetString("EnterSecretKeyTitle");

        /// <summary>
        /// Gets the resource GenerateSecretKeyDescription.
        /// </summary>
        public string GenerateSecretKeyDescription => _resources.GetString("GenerateSecretKeyDescription");

        /// <summary>
        /// Gets the resource GenerateSecretKeyPrint.
        /// </summary>
        public string GenerateSecretKeyPrint => _resources.GetString("GenerateSecretKeyPrint");

        /// <summary>
        /// Gets the resource GenerateSecretKeySave.
        /// </summary>
        public string GenerateSecretKeySave => _resources.GetString("GenerateSecretKeySave");

        /// <summary>
        /// Gets the resource GenerateSecretKeyTitle.
        /// </summary>
        public string GenerateSecretKeyTitle => _resources.GetString("GenerateSecretKeyTitle");

        /// <summary>
        /// Gets the resource GenerateSecretKeyYourKey.
        /// </summary>
        public string GenerateSecretKeyYourKey => _resources.GetString("GenerateSecretKeyYourKey");

        /// <summary>
        /// Gets the resource MaybeLater.
        /// </summary>
        public string MaybeLater => _resources.GetString("MaybeLater");

        /// <summary>
        /// Gets the resource NewOrReturningUserDescription.
        /// </summary>
        public string NewOrReturningUserDescription => _resources.GetString("NewOrReturningUserDescription");

        /// <summary>
        /// Gets the resource NewOrReturningUserNewUser.
        /// </summary>
        public string NewOrReturningUserNewUser => _resources.GetString("NewOrReturningUserNewUser");

        /// <summary>
        /// Gets the resource NewOrReturningUserReturningUser.
        /// </summary>
        public string NewOrReturningUserReturningUser => _resources.GetString("NewOrReturningUserReturningUser");

        /// <summary>
        /// Gets the resource NewOrReturningUserTitle.
        /// </summary>
        public string NewOrReturningUserTitle => _resources.GetString("NewOrReturningUserTitle");

        /// <summary>
        /// Gets the resource Next.
        /// </summary>
        public string Next => _resources.GetString("Next");

        /// <summary>
        /// Gets the resource PlainTextFile.
        /// </summary>
        public string PlainTextFile => _resources.GetString("PlainTextFile");

        /// <summary>
        /// Gets the resource RegisterToCloudServiceDescription.
        /// </summary>
        public string RegisterToCloudServiceDescription => _resources.GetString("RegisterToCloudServiceDescription");

        /// <summary>
        /// Gets the resource RegisterToCloudServiceTitle.
        /// </summary>
        public string RegisterToCloudServiceTitle => _resources.GetString("RegisterToCloudServiceTitle");

        /// <summary>
        /// Gets the resource SecretKeyFileName.
        /// </summary>
        public string SecretKeyFileName => _resources.GetString("SecretKeyFileName");

        /// <summary>
        /// Gets the resource SecretKeyPrintTitle.
        /// </summary>
        public string SecretKeyPrintTitle => _resources.GetString("SecretKeyPrintTitle");

        /// <summary>
        /// Gets the resource SignInToCloudServiceDescription.
        /// </summary>
        public string SignInToCloudServiceDescription => _resources.GetString("SignInToCloudServiceDescription");

        /// <summary>
        /// Gets the resource SignInToCloudServiceTitle.
        /// </summary>
        public string SignInToCloudServiceTitle => _resources.GetString("SignInToCloudServiceTitle");

        /// <summary>
        /// Gets the resource SynchronizationInProgress.
        /// </summary>
        public string SynchronizationInProgress => _resources.GetString("SynchronizationInProgress");

        /// <summary>
        /// Gets the resource WelcomeDescription.
        /// </summary>
        public string WelcomeDescription => _resources.GetString("WelcomeDescription");

        /// <summary>
        /// Gets the resource WelcomeTitle.
        /// </summary>
        public string WelcomeTitle => _resources.GetString("WelcomeTitle");

        /// <summary>
        /// Gets the resource WindowsHelloConfigure.
        /// </summary>
        public string WindowsHelloConfigure => _resources.GetString("WindowsHelloConfigure");

        /// <summary>
        /// Gets the resource WindowsHelloDescription.
        /// </summary>
        public string WindowsHelloDescription => _resources.GetString("WindowsHelloDescription");

        /// <summary>
        /// Gets the resource WindowsHelloSetting.
        /// </summary>
        public string WindowsHelloSetting => _resources.GetString("WindowsHelloSetting");

        /// <summary>
        /// Gets the resource WindowsHelloTitle.
        /// </summary>
        public string WindowsHelloTitle => _resources.GetString("WindowsHelloTitle");
    }

    public class InputDialogStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/InputDialog");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource AccountTitlePlaceholder.
        /// </summary>
        public string AccountTitlePlaceholder => _resources.GetString("AccountTitlePlaceholder");

        /// <summary>
        /// Gets the resource AddAccountPrimaryButton.
        /// </summary>
        public string AddAccountPrimaryButton => _resources.GetString("AddAccountPrimaryButton");

        /// <summary>
        /// Gets the resource AddAccountTitle.
        /// </summary>
        public string AddAccountTitle => _resources.GetString("AddAccountTitle");

        /// <summary>
        /// Gets the resource AddCategoryPrimaryButton.
        /// </summary>
        public string AddCategoryPrimaryButton => _resources.GetString("AddCategoryPrimaryButton");

        /// <summary>
        /// Gets the resource AddCategoryTitle.
        /// </summary>
        public string AddCategoryTitle => _resources.GetString("AddCategoryTitle");

        /// <summary>
        /// Gets the resource CategoryNamePlaceholder.
        /// </summary>
        public string CategoryNamePlaceholder => _resources.GetString("CategoryNamePlaceholder");

        /// <summary>
        /// Gets the resource RenamePrimaryButton.
        /// </summary>
        public string RenamePrimaryButton => _resources.GetString("RenamePrimaryButton");

        /// <summary>
        /// Gets the resource RenameTitle.
        /// </summary>
        public string RenameTitle => _resources.GetString("RenameTitle");

        /// <summary>
        /// Gets the resource SecondaryButton.
        /// </summary>
        public string SecondaryButton => _resources.GetString("SecondaryButton");
    }

    public class LicenseKeyDataStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/LicenseKeyData");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource Company.
        /// </summary>
        public string Company => _resources.GetString("Company");

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");

        /// <summary>
        /// Gets the resource LicenseKey.
        /// </summary>
        public string LicenseKey => _resources.GetString("LicenseKey");

        /// <summary>
        /// Gets the resource LicenseTo.
        /// </summary>
        public string LicenseTo => _resources.GetString("LicenseTo");

        /// <summary>
        /// Gets the resource LinkedEmailAddress.
        /// </summary>
        public string LinkedEmailAddress => _resources.GetString("LinkedEmailAddress");
    }

    public class MainPageStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/MainPage");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource AddACategory.
        /// </summary>
        public string AddACategory => _resources.GetString("AddACategory");

        /// <summary>
        /// Gets the resource Delete.
        /// </summary>
        public string Delete => _resources.GetString("Delete");

        /// <summary>
        /// Gets the resource DeleteConfirmationDescription.
        /// </summary>
        public string DeleteConfirmationDescription => _resources.GetString("DeleteConfirmationDescription");

        /// <summary>
        /// Gets the resource DeleteConfirmationTitle.
        /// </summary>
        public string DeleteConfirmationTitle => _resources.GetString("DeleteConfirmationTitle");

        /// <summary>
        /// Gets the resource DeleteConfirmationTitle with format.
        /// </summary>
        public string GetFormattedDeleteConfirmationTitle(string param0)
        {
            return string.Format(DeleteConfirmationTitle, param0);
        }

        /// <summary>
        /// Gets the resource No.
        /// </summary>
        public string No => _resources.GetString("No");

        /// <summary>
        /// Gets the resource Rename.
        /// </summary>
        public string Rename => _resources.GetString("Rename");

        /// <summary>
        /// Gets the resource Search.
        /// </summary>
        public string Search => _resources.GetString("Search");

        /// <summary>
        /// Gets the resource Settings.
        /// </summary>
        public string Settings => _resources.GetString("Settings");

        /// <summary>
        /// Gets the resource Yes.
        /// </summary>
        public string Yes => _resources.GetString("Yes");
    }

    public class OneDriveStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/OneDrive");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");
    }

    public class OtherDataStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/OtherData");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");

        /// <summary>
        /// Gets the resource Name.
        /// </summary>
        public string Name => _resources.GetString("Name");

        /// <summary>
        /// Gets the resource Value.
        /// </summary>
        public string Value => _resources.GetString("Value");
    }

    public class PasswordGeneratorDialogStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/PasswordGeneratorDialog");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource EasyToRead.
        /// </summary>
        public string EasyToRead => _resources.GetString("EasyToRead");

        /// <summary>
        /// Gets the resource ErrorOccured.
        /// </summary>
        public string ErrorOccured => _resources.GetString("ErrorOccured");

        /// <summary>
        /// Gets the resource FetchingDictionary.
        /// </summary>
        public string FetchingDictionary => _resources.GetString("FetchingDictionary");

        /// <summary>
        /// Gets the resource NoInternet.
        /// </summary>
        public string NoInternet => _resources.GetString("NoInternet");

        /// <summary>
        /// Gets the resource PasswordLength.
        /// </summary>
        public string PasswordLength => _resources.GetString("PasswordLength");

        /// <summary>
        /// Gets the resource PrimaryButton.
        /// </summary>
        public string PrimaryButton => _resources.GetString("PrimaryButton");

        /// <summary>
        /// Gets the resource Refresh.
        /// </summary>
        public string Refresh => _resources.GetString("Refresh");

        /// <summary>
        /// Gets the resource SecondaryButton.
        /// </summary>
        public string SecondaryButton => _resources.GetString("SecondaryButton");

        /// <summary>
        /// Gets the resource Title.
        /// </summary>
        public string Title => _resources.GetString("Title");

        /// <summary>
        /// Gets the resource WordDictionaryUrl.
        /// </summary>
        public string WordDictionaryUrl => _resources.GetString("WordDictionaryUrl");
    }

    public class PaymentCardDataStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/PaymentCardData");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource AmericanExpress.
        /// </summary>
        public string AmericanExpress => _resources.GetString("AmericanExpress");

        /// <summary>
        /// Gets the resource BankName.
        /// </summary>
        public string BankName => _resources.GetString("BankName");

        /// <summary>
        /// Gets the resource CardCryptogram.
        /// </summary>
        public string CardCryptogram => _resources.GetString("CardCryptogram");

        /// <summary>
        /// Gets the resource CardExpirationDate.
        /// </summary>
        public string CardExpirationDate => _resources.GetString("CardExpirationDate");

        /// <summary>
        /// Gets the resource CardHolder.
        /// </summary>
        public string CardHolder => _resources.GetString("CardHolder");

        /// <summary>
        /// Gets the resource CardNumber.
        /// </summary>
        public string CardNumber => _resources.GetString("CardNumber");

        /// <summary>
        /// Gets the resource CardType.
        /// </summary>
        public string CardType => _resources.GetString("CardType");

        /// <summary>
        /// Gets the resource Discovery.
        /// </summary>
        public string Discovery => _resources.GetString("Discovery");

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");

        /// <summary>
        /// Gets the resource Mastercard.
        /// </summary>
        public string Mastercard => _resources.GetString("Mastercard");

        /// <summary>
        /// Gets the resource Other.
        /// </summary>
        public string Other => _resources.GetString("Other");

        /// <summary>
        /// Gets the resource Visa.
        /// </summary>
        public string Visa => _resources.GetString("Visa");
    }

    public class RateAndReviewAppStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/RateAndReviewApp");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource EnjoyingCloseButtonText.
        /// </summary>
        public string EnjoyingCloseButtonText => _resources.GetString("EnjoyingCloseButtonText");

        /// <summary>
        /// Gets the resource EnjoyingMessage.
        /// </summary>
        public string EnjoyingMessage => _resources.GetString("EnjoyingMessage");

        /// <summary>
        /// Gets the resource EnjoyingPrimaryButtonText.
        /// </summary>
        public string EnjoyingPrimaryButtonText => _resources.GetString("EnjoyingPrimaryButtonText");

        /// <summary>
        /// Gets the resource EnjoyingTitle.
        /// </summary>
        public string EnjoyingTitle => _resources.GetString("EnjoyingTitle");

        /// <summary>
        /// Gets the resource FeedbackCloseButtonText.
        /// </summary>
        public string FeedbackCloseButtonText => _resources.GetString("FeedbackCloseButtonText");

        /// <summary>
        /// Gets the resource FeedbackMessage.
        /// </summary>
        public string FeedbackMessage => _resources.GetString("FeedbackMessage");

        /// <summary>
        /// Gets the resource FeedbackPrimaryButtonText.
        /// </summary>
        public string FeedbackPrimaryButtonText => _resources.GetString("FeedbackPrimaryButtonText");

        /// <summary>
        /// Gets the resource FeedbackTitle.
        /// </summary>
        public string FeedbackTitle => _resources.GetString("FeedbackTitle");

        /// <summary>
        /// Gets the resource RateCloseButtonText.
        /// </summary>
        public string RateCloseButtonText => _resources.GetString("RateCloseButtonText");

        /// <summary>
        /// Gets the resource RateMessage.
        /// </summary>
        public string RateMessage => _resources.GetString("RateMessage");

        /// <summary>
        /// Gets the resource RatePrimaryButtonText.
        /// </summary>
        public string RatePrimaryButtonText => _resources.GetString("RatePrimaryButtonText");

        /// <summary>
        /// Gets the resource RateSecondaryButtonText.
        /// </summary>
        public string RateSecondaryButtonText => _resources.GetString("RateSecondaryButtonText");

        /// <summary>
        /// Gets the resource RateTitle.
        /// </summary>
        public string RateTitle => _resources.GetString("RateTitle");
    }

    public class SettingsPageStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/SettingsPage");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource About.
        /// </summary>
        public string About => _resources.GetString("About");

        /// <summary>
        /// Gets the resource AskSecretKeyOccasionallyDescription.
        /// </summary>
        public string AskSecretKeyOccasionallyDescription => _resources.GetString("AskSecretKeyOccasionallyDescription");

        /// <summary>
        /// Gets the resource AskSecretKeyOccasionallySetting.
        /// </summary>
        public string AskSecretKeyOccasionallySetting => _resources.GetString("AskSecretKeyOccasionallySetting");

        /// <summary>
        /// Gets the resource AskSecretKeyOccasionallyTitle.
        /// </summary>
        public string AskSecretKeyOccasionallyTitle => _resources.GetString("AskSecretKeyOccasionallyTitle");

        /// <summary>
        /// Gets the resource CloudStorageServiceDescription.
        /// </summary>
        public string CloudStorageServiceDescription => _resources.GetString("CloudStorageServiceDescription");

        /// <summary>
        /// Gets the resource CloudStorageServiceTitle.
        /// </summary>
        public string CloudStorageServiceTitle => _resources.GetString("CloudStorageServiceTitle");

        /// <summary>
        /// Gets the resource ContributorList.
        /// </summary>
        public string ContributorList => _resources.GetString("ContributorList");

        /// <summary>
        /// Gets the resource Contributors.
        /// </summary>
        public string Contributors => _resources.GetString("Contributors");

        /// <summary>
        /// Gets the resource DiscoverOtherApps.
        /// </summary>
        public string DiscoverOtherApps => _resources.GetString("DiscoverOtherApps");

        /// <summary>
        /// Gets the resource General.
        /// </summary>
        public string General => _resources.GetString("General");

        /// <summary>
        /// Gets the resource License.
        /// </summary>
        public string License => _resources.GetString("License");

        /// <summary>
        /// Gets the resource LockAfterInactivityDescription.
        /// </summary>
        public string LockAfterInactivityDescription => _resources.GetString("LockAfterInactivityDescription");

        /// <summary>
        /// Gets the resource LockAfterInactivitySetting.
        /// </summary>
        public string LockAfterInactivitySetting => _resources.GetString("LockAfterInactivitySetting");

        /// <summary>
        /// Gets the resource LockAfterInactivityTitle.
        /// </summary>
        public string LockAfterInactivityTitle => _resources.GetString("LockAfterInactivityTitle");

        /// <summary>
        /// Gets the resource LockAfterInactivity_FifteenMinutes.
        /// </summary>
        public string LockAfterInactivity_FifteenMinutes => _resources.GetString("LockAfterInactivity_FifteenMinutes");

        /// <summary>
        /// Gets the resource LockAfterInactivity_FiveMinutes.
        /// </summary>
        public string LockAfterInactivity_FiveMinutes => _resources.GetString("LockAfterInactivity_FiveMinutes");

        /// <summary>
        /// Gets the resource LockAfterInactivity_Never.
        /// </summary>
        public string LockAfterInactivity_Never => _resources.GetString("LockAfterInactivity_Never");

        /// <summary>
        /// Gets the resource LockAfterInactivity_OneHour.
        /// </summary>
        public string LockAfterInactivity_OneHour => _resources.GetString("LockAfterInactivity_OneHour");

        /// <summary>
        /// Gets the resource LockAfterInactivity_TenMinutes.
        /// </summary>
        public string LockAfterInactivity_TenMinutes => _resources.GetString("LockAfterInactivity_TenMinutes");

        /// <summary>
        /// Gets the resource LockAfterInactivity_ThirtyMinutes.
        /// </summary>
        public string LockAfterInactivity_ThirtyMinutes => _resources.GetString("LockAfterInactivity_ThirtyMinutes");

        /// <summary>
        /// Gets the resource Logs.
        /// </summary>
        public string Logs => _resources.GetString("Logs");

        /// <summary>
        /// Gets the resource MadeWithLove.
        /// </summary>
        public string MadeWithLove => _resources.GetString("MadeWithLove");

        /// <summary>
        /// Gets the resource OpenSource.
        /// </summary>
        public string OpenSource => _resources.GetString("OpenSource");

        /// <summary>
        /// Gets the resource PrivacyStatement.
        /// </summary>
        public string PrivacyStatement => _resources.GetString("PrivacyStatement");

        /// <summary>
        /// Gets the resource Security.
        /// </summary>
        public string Security => _resources.GetString("Security");

        /// <summary>
        /// Gets the resource SignOut.
        /// </summary>
        public string SignOut => _resources.GetString("SignOut");

        /// <summary>
        /// Gets the resource SubmitFeedback.
        /// </summary>
        public string SubmitFeedback => _resources.GetString("SubmitFeedback");

        /// <summary>
        /// Gets the resource SyncCloudDescription.
        /// </summary>
        public string SyncCloudDescription => _resources.GetString("SyncCloudDescription");

        /// <summary>
        /// Gets the resource SyncCloudSetting.
        /// </summary>
        public string SyncCloudSetting => _resources.GetString("SyncCloudSetting");

        /// <summary>
        /// Gets the resource SyncCloudTitle.
        /// </summary>
        public string SyncCloudTitle => _resources.GetString("SyncCloudTitle");

        /// <summary>
        /// Gets the resource Synchronization.
        /// </summary>
        public string Synchronization => _resources.GetString("Synchronization");

        /// <summary>
        /// Gets the resource SyncNow.
        /// </summary>
        public string SyncNow => _resources.GetString("SyncNow");

        /// <summary>
        /// Gets the resource ThemeConfigure.
        /// </summary>
        public string ThemeConfigure => _resources.GetString("ThemeConfigure");

        /// <summary>
        /// Gets the resource ThemeDark.
        /// </summary>
        public string ThemeDark => _resources.GetString("ThemeDark");

        /// <summary>
        /// Gets the resource ThemeDefault.
        /// </summary>
        public string ThemeDefault => _resources.GetString("ThemeDefault");

        /// <summary>
        /// Gets the resource ThemeDescription.
        /// </summary>
        public string ThemeDescription => _resources.GetString("ThemeDescription");

        /// <summary>
        /// Gets the resource ThemeLight.
        /// </summary>
        public string ThemeLight => _resources.GetString("ThemeLight");

        /// <summary>
        /// Gets the resource ThemeTitle.
        /// </summary>
        public string ThemeTitle => _resources.GetString("ThemeTitle");

        /// <summary>
        /// Gets the resource ThirdPartyServices.
        /// </summary>
        public string ThirdPartyServices => _resources.GetString("ThirdPartyServices");

        /// <summary>
        /// Gets the resource ThirdPartySoftware.
        /// </summary>
        public string ThirdPartySoftware => _resources.GetString("ThirdPartySoftware");

        /// <summary>
        /// Gets the resource TwoFactorDescription.
        /// </summary>
        public string TwoFactorDescription => _resources.GetString("TwoFactorDescription");

        /// <summary>
        /// Gets the resource TwoFactorSetting.
        /// </summary>
        public string TwoFactorSetting => _resources.GetString("TwoFactorSetting");

        /// <summary>
        /// Gets the resource TwoFactorTitle.
        /// </summary>
        public string TwoFactorTitle => _resources.GetString("TwoFactorTitle");

        /// <summary>
        /// Gets the resource WarningNoSecurity.
        /// </summary>
        public string WarningNoSecurity => _resources.GetString("WarningNoSecurity");

        /// <summary>
        /// Gets the resource WindowsHelloConfigure.
        /// </summary>
        public string WindowsHelloConfigure => _resources.GetString("WindowsHelloConfigure");

        /// <summary>
        /// Gets the resource WindowsHelloDescription.
        /// </summary>
        public string WindowsHelloDescription => _resources.GetString("WindowsHelloDescription");

        /// <summary>
        /// Gets the resource WindowsHelloSetting.
        /// </summary>
        public string WindowsHelloSetting => _resources.GetString("WindowsHelloSetting");

        /// <summary>
        /// Gets the resource WindowsHelloTitle.
        /// </summary>
        public string WindowsHelloTitle => _resources.GetString("WindowsHelloTitle");
    }

    public class SetupTwoFactorAuthenticationStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/SetupTwoFactorAuthentication");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource CodeGenerated.
        /// </summary>
        public string CodeGenerated => _resources.GetString("CodeGenerated");

        /// <summary>
        /// Gets the resource ConfirmEmailAddress.
        /// </summary>
        public string ConfirmEmailAddress => _resources.GetString("ConfirmEmailAddress");

        /// <summary>
        /// Gets the resource EmailAddress.
        /// </summary>
        public string EmailAddress => _resources.GetString("EmailAddress");

        /// <summary>
        /// Gets the resource Instruction1.
        /// </summary>
        public string Instruction1 => _resources.GetString("Instruction1");

        /// <summary>
        /// Gets the resource Instruction2.
        /// </summary>
        public string Instruction2 => _resources.GetString("Instruction2");

        /// <summary>
        /// Gets the resource Instruction3.
        /// </summary>
        public string Instruction3 => _resources.GetString("Instruction3");

        /// <summary>
        /// Gets the resource PrimaryButton.
        /// </summary>
        public string PrimaryButton => _resources.GetString("PrimaryButton");

        /// <summary>
        /// Gets the resource QrCodeGeneratedAfterEmail.
        /// </summary>
        public string QrCodeGeneratedAfterEmail => _resources.GetString("QrCodeGeneratedAfterEmail");

        /// <summary>
        /// Gets the resource SecondaryButton.
        /// </summary>
        public string SecondaryButton => _resources.GetString("SecondaryButton");

        /// <summary>
        /// Gets the resource Title.
        /// </summary>
        public string Title => _resources.GetString("Title");
    }

    public class WiFiCredentialDataStrings : INotifyPropertyChanged
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("PaZword.Localization/WiFiCredentialData");

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");

        /// <summary>
        /// Gets the resource Password.
        /// </summary>
        public string Password => _resources.GetString("Password");

        /// <summary>
        /// Gets the resource Ssid.
        /// </summary>
        public string Ssid => _resources.GetString("Ssid");
    }
}

#pragma warning restore 67 // CS0067 The event 'event' is never used