  
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaZword.Core
{
    internal static class ServicesKeys 
    {
        internal const string DropBoxAppKey = "uxd190eeszm7en1";
        internal const string DropBoxRedirectUri = "https://localhost/authorize";
        internal const string OneDriveClientId = "c048a998-de91-40a8-a8f5-3e8da7ef4c9a";
        internal const string OneDriveRedirectUri = "https://login.microsoftonline.com/common/oauth2/nativeclient";
        internal const string RiteKitClientId = "0c3faa0a604e47b6e1c35b0195b2208a993188f663b4";
        internal const string SupportEmailAddress = "support@velersoftware.com";
        internal const string TwoFactorAuthenticationServiceUrl = "https://pazword.velersoftware.com/services/serviceUser.php";
    }
}